### ISSUE TITLE
Won't Compile Due to error.h Not Found on MacOS

### ISSUE THREAD

**Issue by chfanghr** [rust-embedded/itm#26]
This problem is beacuse apple-clang redirect errno.h to cerror. Change `#include <errno.h>` to `#include <cerror>` should fix the problem.

**Comment by jonas-schievink** [comment]
Can you post the error message and context? This shouldn't require any C(++) code from what I can tell

**Comment by chfanghr** [comment]
Sorry for posting an issue here. After some research, I found that the problem is caused by apple-calng compiler, which no longer put `/usr/include` in its include path by default(MacOS Catalina, apple-clang 11), so that anything using stdlib should manually set CFALGS to compile. 

 Related issue: https://github.com/rust-lang/backtrace-rs/issues/296

Set `CFLAGS` to `-I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include` should fix the problem.
