### ISSUE TITLE
Feature idea : add option to record received time of ITM message

### ISSUE THREAD

**Issue by JOE1994** [rust-embedded/itm#34]
[STM32CubeIDE](https://www.st.com/en/development-tools/stm32cubeide.html) has a feature that shows the received time of an ITM data,
and it seems to be provide a convenient way for profiling embedded apps.

![image](https://user-images.githubusercontent.com/10286488/87102271-67d4de80-c21f-11ea-9181-1d716060ae3f.png)

I thought this feature could be useful when added to the `itm-dump` tool.
I'm not an expert with ITM or embedded stuff, so I first wanted to ask whether this feature would fit well with the `itm-dump` tool.
I can try implementing the feature in the near future.

Reference
* http://blog.atollic.com/cortex-m-debugging-measure-execution-time-using-swv/itm

Thank you for reading :crab:

**Comment by JOE1994** [comment]
I've come to think that rather than implementing this functionality on the `itmdump` side, it might be better to create an API like `iprint_with_timestamp` in the `cortex_m` crate.. I'll close this issue..

**Comment by ryankurte** [comment]
seems like a super interesting idea! would definitely come in handy for some timing-specific debugging i have been doing.
i haven't used ITM much but would expect this to be a combination of support for receiving timestamps in `itmdump` as well as itm client extensions.

as to where to put this i would be inclined to fork `itmdump` for the receiver side to support receiving timestamps, and maybe look at feature for [itm_logger](https://github.com/cs2dsb/itm_logger.rs) or [cortex-m-log](https://github.com/DoumanAsh/cortex-m-log) to support client-side-timestamping? (disclaimer: i have not used either of `itm_logger` or `corex-m-log` they just seem roughly in line with your goals)

**Comment by therealprof** [comment]
@JOE1994 Have you looked into probe.rs and its RTT feature?

**Comment by JOE1994** [comment]
> @JOE1994 Have you looked into probe.rs and its RTT feature?

I've never tried `probe.rs` before! (I've been using `gdb` & `openocd` for flashing & debugging)

Thank you for the pointers! I'll take a good look at it :smile_cat:
